name: clarity
description: Clarity â€” Flutter MVVM app with Firebase, offline mode, and notifications
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  circular_countdown_timer: ^0.2.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.10 
  android_intent_plus: ^6.0.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  android_alarm_manager_plus: ^5.0.0
  table_calendar: ^3.2.0
  
  
  
  


  # --- State management ---
  provider: ^6.1.5+1

  # --- Firebase core packages ---
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3
  google_sign_in: ^6.1.5

  # --- Notifications / time ---
  

  # --- Notifications / time ---
  flutter_local_notifications: ^19.4.2
  flutter_timezone: ^4.1.0
  
 
  


  timezone: ^0.10.1


  # --- Utilities ---
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/images/app_image/clematis.png"
  remove_alpha: true
  remove_alpha_ios: true

flutter:
    uses-material-design: true

